create table if not exists public.learning_events (
    id bigint generated by default as identity primary key,
    symbol text not null,
    signal_date date not null,
    reference_date date not null,
    rise_percent double precision not null check (rise_percent > 5.0),
    technical_features jsonb not null default '{}'::jsonb,
    news_features jsonb not null default '{}'::jsonb,
    sector_features jsonb not null default '{}'::jsonb,
    source_quality double precision,
    created_at timestamptz not null default now(),
    constraint learning_events_symbol_signal_date_key
        unique (symbol, signal_date)
);

create index if not exists learning_events_signal_date_idx
    on public.learning_events (signal_date);

create index if not exists learning_events_symbol_idx
    on public.learning_events (symbol);
