create table if not exists public.model_versions (
    id bigint generated by default as identity primary key,
    version text not null unique,
    status text not null,
    accuracy double precision,
    precision double precision,
    recall double precision,
    sample_count integer not null default 0,
    pattern_count integer not null default 0,
    training_start timestamptz,
    training_end timestamptz,
    created_at timestamptz not null default now(),
    activated_at timestamptz
);

create index if not exists model_versions_status_idx
    on public.model_versions (status);

create index if not exists model_versions_created_at_idx
    on public.model_versions (created_at);
