create table if not exists public.news_items (
    id bigint generated by default as identity primary key,
    symbol text not null,
    title text not null,
    url text not null,
    source text not null,
    published_at timestamptz not null,
    content_hash text not null,
    created_at timestamptz not null default now(),
    constraint news_items_symbol_content_hash_key
        unique (symbol, content_hash)
);

create index if not exists news_items_symbol_published_at_idx
    on public.news_items (symbol, published_at desc);

create index if not exists news_items_published_at_idx
    on public.news_items (published_at desc);
