LEARNING_THRESHOLD_PERCENT = 5.0

TOP_PREDICTIONS_COUNT = 10

DEFAULT_LOOKBACK_DAYS = 365

MODEL_VERSION = "0.1.0"

MARKET_TIMEZONE = "Europe/Istanbul"

LEARNING_ENABLED_BY_DEFAULT = True

LIVE_TRADING_ENABLED = False
